#!/bin/bash
api1=https://plive.48.cn/livesystem/api/live/v1/memberLivePage
api2=https://pother.48.cn/othersystem/api/version/v1/download/fansapp/android
randomString=$(cat /proc/sys/kernel/random/uuid)
thread=$(grep processor /proc/cpuinfo | wc -l)
GETOPT=`getopt -o j: --long job: -n 'exit' -- "$@"`
data="{"lastTime": 0, "groupId": 0, "memberId": 0, "limit": 20000}"
jq="{title, subTitle: {raw: .subTitle, base64: (.subTitle|@base64)}, picPath, startTime: {timeStamp: .startTime, dateTime: (.startTime/1000+28800|todate)}, memberId, liveType, streamPath}"
LatestVersion(){
	curl -sI $api2 | grep -Po '\d+\.\d+\.\d+' | tail -1 | tee pocket48_version.conf
}
if [ -f pocket48_version.conf ] ; then
	now=$(date +%Y-%m-%dT%TZ | sed 's/^/"&/ ; s/$/&"/' | jq fromdate)
	modifiedTime=$(ls --full-time -l pocket48_version.conf | awk -F "." '{print $1}' | awk '{print $6,$7}' | sed 's/^/"&/ ; s/ /T/ ; s/$/&Z"/' | jq fromdate)
	if [ $(awk "BEGIN{print ($now-$modifiedTime)}") -lt 2592000 ] ; then
		version=$(cat pocket48_version.conf)
	else
		version=$(LatestVersion)
	fi
else
	version=$(LatestVersion)
fi
header1="Content-Type: application/json"
header2="version: $version"
header3="os: android"
eval set -- "$GETOPT"
while true ; do
	case "$1" in
		-j|--job) thread="$2" ; shift 2 ;;
		--) shift ; break ;;
		*) exit 1 ;;
	esac
done
echo "Downloading JSON file from Koudai48 API..."
curl -s -X POST $api1 -H "$header1" -H "$header2" -H "$header3" --data "$data" | jq ".content.reviewList | map($jq | setpath([\"picPath\"];(.picPath/\",\")))" | sed 's/\/mediasource/https:\/\/source.48.cn&/g' >> "$randomString"
memberId=$(awk -F "," '{print $2}' MemberID.csv | tail -n +2)
Do(){
	memberName=$(awk -F "," "\$2==\"$1\" {print \$1}" MemberID.csv)
	memberID=$(echo $1 | awk '{printf("%06d\n",$1)}')
	filename1="$memberID-$memberName.json"
	filename2="$memberID-$memberName.txt"
	jq "map(select(.memberId == $1))" $2 > "../normal/$filename1"
	sum=$(jq '.[] | .streamPath' "../normal/$filename1" | wc -l)
	echo "[normal] $sum URL(s) written in ../normal/$filename1"
	jq '.[] | {(.startTime.dateTime): .streamPath}' "../normal/$filename1" | grep -Po '"[^{|}]*' > "../quiet/$filename2"
	echo "[quiet] $sum URL(s) written in ../quiet/$filename2"
}
export -f Do
parallel -j "$thread" -k Do ::: "$memberId" ::: "$randomString"
echo "Cleaning up..."
rm "$randomString"
