#!/bin/bash
thread=$(grep processor /proc/cpuinfo | wc -l)
GETOPT=`getopt -o j: --long job: -n 'exit' -- "$@"`
eval set -- "$GETOPT"
while true ; do
	case "$1" in
		-j|--job) thread="$2" ; shift 2 ;;
		--) shift ; break ;;
		*) exit 1 ;;
	esac
done
echo "Downloading JSON file from Koudai48 API..."
./pkt48 -r -L all -N >> temp.json
memberId=$(awk -F "," '{print $2}' MemberID.csv | tail -n +2)
Do(){
	memberName=$(awk -F "," "\$2==\"$1\" {print \$1}" MemberID.csv)
	memberID=$(echo $1 | awk '{printf("%06d\n",$1)}')
	filename1="$memberID-$memberName.json"
	filename2="$memberID-$memberName.txt"
	jq "map(select(.memberId == $1))" temp.json > "../normal/$filename1"
	sum=$(jq '.[] | .streamPath' "../normal/$filename1" | wc -l)
	echo "[normal] $sum URL(s) written in ../normal/$filename1"
	jq '.[] | {(.startTime.dateTime): .streamPath}' "../normal/$filename1" | grep -Po '"[^{|}]*' > "../quiet/$filename2"
	echo "[quiet] $sum URL(s) written in ../quiet/$filename2"
}
export -f Do
parallel -j "$thread" -k Do ::: "$memberId"
echo "Cleaning up..."
rm temp.json
